PROG1=master



all:

	$(CC) $(PROG1).c -o ../bin/$(PROG1)
	#$(CC)  $(PROG19).c -o bin/$(PROG19) `pkg-config --cflags --libs libmodbus`
	#$(CC)  -o bin/$(PROG20) $(PROG20).c cJSON.c -lm -lcurl


clean:
	rm -rf *.o
	rm -rf ../bin/$(PROG1)




